title: GenoCAT
description: >-
baseurl: ""
url: ""
github_username: hms-dbmi

markdown: kramdown
theme: uswds-jekyll
plugins:
  - jekyll-feed
collections:
  tools:
      output: true
  attributes:
      output: true
